---
AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  NewCops: enable

Layout/IndentationWidth:
  Width: 4

Layout/HeredocIndentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - table
  EnforcedColonStyle:
    - table

Layout/SpaceAroundOperators:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
    EnforcedStyleForMultiline: comma

Style/RedundantReturn:
  Enabled: false

# don't break older Rubies just because of style
Style/RedundantBegin:
  Enabled: false
